### ISSUE TITLE
UI is pretty unusable (laptop)

### ISSUE THREAD

**Issue by Jacob-Lockwood** [bsoelch/OneChar.js#1]
ForWhile looks like a very interesting and cool language, and I wanted to try playing around with it. Unfortunately, I'm running into issues using the online interpreter.

This is what the online interpreter looks like on my device (a 13-inch MacBook Pro, using a chromium-based browser; I have my browser window at a reasonably large size):

![Screen shot of the messy layout](https://github.com/bsoelch/OneChar.js/assets/68607796/6ad7f82f-3616-4f17-879d-156beb0066a3)

The UI is all overlapping, with some elements way to big and with information like Input and Output being covered up, and the text is really small. I took a look at the source and realized you have the page styled in a pretty convoluted way (No offense :smile:). I would consider using Flexbox or CSS Grid styling for this—it would take about 5 lines of code and make the layout much easier to deal with. 

If you want, I can send a PR re-factoring the layout.

**Comment by bsoelch** [comment]
I fixed the overlapping UI (as far as I can tell).

The layout is messed up because it was only intended to be a minimum working solution to have a UI for the Interpreter.

Fell free to improve the layout (I only have minimal HTML/CSS skills), but please do not break the following use cases:
* The HTML-file should work correctly when executed as a local file without being connected to the Internet
* The page should work in Firefox

**Comment by Jacob-Lockwood** [comment]
It works much better now, thank you!
